version: '2'
services:
  spark-master:
    image: bde2020/spark-master:2.4.5-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:7077"
    volumes:
      # - ./data:/data
      - /home/rs/Desktop/ntfs/nytaxi:/home/rs/Desktop/ntfs/nytaxi
      - /tmp/spark-events-local:/tmp/spark-events
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
      - SPARK_DRIVER_MEMORY=2G
      - SPARK_EXECUTOR_MEMORY=2G
  spark-worker-1:
    image: bde2020/spark-worker:2.4.5-hadoop2.7
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      # - ./data:/data
      - /home/rs/Desktop/ntfs/nytaxi:/home/rs/Desktop/ntfs/nytaxi
      - /tmp/spark-events-local:/tmp/spark-events
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
      - SPARK_DRIVER_MEMORY=2G
      - SPARK_EXECUTOR_MEMORY=2G
  spark-worker-2:
    image: bde2020/spark-worker:2.4.5-hadoop2.7
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    volumes:
      # - ./data:/data
      - /home/rs/Desktop/ntfs/nytaxi:/home/rs/Desktop/ntfs/nytaxi
      - /tmp/spark-events-local:/tmp/spark-events
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
      - SPARK_DRIVER_MEMORY=2G
      - SPARK_EXECUTOR_MEMORY=2G
  spark-worker-3:
    image: bde2020/spark-worker:2.4.5-hadoop2.7
    container_name: spark-worker-3
    depends_on:
      - spark-master
    ports:
      - "8083:8081"
    volumes:
      # - ./data:/data
      - /home/rs/Desktop/ntfs/nytaxi:/home/rs/Desktop/ntfs/nytaxi
      - /tmp/spark-events-local:/tmp/spark-events
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
      - SPARK_DRIVER_MEMORY=2G
      - SPARK_EXECUTOR_MEMORY=2G
#  spark-history-server:
#    image: bde2020/spark-history-server:3.1.1-hadoop3.2
#    container_name: spark-history-server
#    depends_on:
#      - spark-master
#    ports:
#      - "18081:18081"
#    volumes:
#      - /tmp/spark-events-local:/tmp/spark-events